<?php
/**
 * Default view for the documentation module.
 * @package views
 */
?>

<h1>
   Documentation
</h1>

<div class="content">
<ul>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/Framework_Contract.pdf"?>" class="pagelink" >Framework Contract</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/Framework_Contract_Public_Presentation.pdf"?>" class="pagelink" >Framework Contract Presentation</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/Subcontract_Gal.doc"?>" class="pagelink" >Contract of Subcontracting Template</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/Confidentiality_Agreement_Template.doc"?>" class="pagelink" >Confidentiality Agreement Template</a>
	</li>
</ul>

</div>